AllCops:
  TargetRubyVersion: 3.1.2
  EnabledByDefault: true
  SuggestExtensions: false
  Include:
    - 'app/**/*.rb'
  Exclude:
    - 'bin/**'
    - 'vendor/**/*'
    - 'config/**/*'
    - './Gemfile'
FrozenStringLiteralComment:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/DocumentationMethod:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Lint/ConstantResolution:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Layout/MultilineMethodArgumentLineBreaks:
  Enabled: false
Style/IdenticalConditionalBranches:
  Enabled: false
Style/MissingElse:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Lint/NumberConversion:
  Enabled: false
Layout/LineLength:
  Max: 159
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Style/OptionHash:
  Enabled: false
Style/SymbolProc:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
Bundler/GemComment:
  Enabled: false
Bundler/GemVersion:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Layout/RedundantLineBreak:
  Enabled: false
