version: "3.9"

services:
  db:
      image: postgres:14
      volumes:
        - ./tmp/db:/var/lib/postgresql/data
      environment:
        POSTGRES_HOST_AUTH_METHOD: "trust"
  web:
    build: .
    command:
      - /bin/bash
      - -c
      - |
        rm -f tmp/pids/server.pid
        bundle exec rails db:create
        bundle exec rails db:migrate
        bundle exec rails s -p 3000 -b 0.0.0.0
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db